<a href="https://colab.research.google.com/github/mahault/ContinuousTraining/blob/main/Numpy_Index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np  # Importing NumPy

# Creating an array with np.arange with values from 0 to 10
arange_array = np.arange(11)

# Grabbing the value at index 8
value_at_index_8 = arange_array[8]

print("Value at index 8:", value_at_index_8)

Value at index 8: 8


In [2]:
# Grabbing the values at indices 1 through 5
values_1_to_5 = arange_array[1:6]

print("Values from index 1 to 5:", values_1_to_5)

Values from index 1 to 5: [1 2 3 4 5]


In [3]:
# Grabbing all values up to (but not including) index 5
values_until_5 = arange_array[:5]

# Grabbing all values after (and including) index 5
values_after_5 = arange_array[5:]

print("Values up to index 5:", values_until_5)
print("Values after index 5:", values_after_5)

Values up to index 5: [0 1 2 3 4]
Values after index 5: [ 5  6  7  8  9 10]


In [4]:
# Broadcasting a single value (e.g., 99) to the first 5 values of the array
arange_array[:5] = 99

print("Array after broadcasting a single value to the first 5 elements:", arange_array)

Array after broadcasting a single value to the first 5 elements: [99 99 99 99 99  5  6  7  8  9 10]


In [5]:
# Getting a slice from index 3 to 8
slice_array = arange_array[3:9]

print("Slice from index 3 to 8:", slice_array)

Slice from index 3 to 8: [99 99  5  6  7  8]


In [6]:
# Resetting the array to its original state with np.arange
original_array = np.arange(11)

# Making a copy of the array
copy_array = original_array.copy()

# Setting all elements of the copy to 100
copy_array[:] = 100

print("Original array:", original_array)
print("Modified copy with all elements set to 100:", copy_array)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10]
Modified copy with all elements set to 100: [100 100 100 100 100 100 100 100 100 100 100]


In [7]:
# Creating a 2D array with 3 lists of 3 numbers each
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Finding the shape of the 2D array
array_shape = two_d_array.shape

print("2D Array:\n", two_d_array)
print("Shape of the 2D array:", array_shape)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the 2D array: (3, 3)


In [8]:
first_row = two_d_array[0]

# Getting the last row
last_row = two_d_array[-1]

print("First row:", first_row)
print("Last row:", last_row)

First row: [1 2 3]
Last row: [7 8 9]


In [9]:
# Getting the element from the first row and second column
element = two_d_array[0, 1]

print("Element at first row and second column:", element)

Element at first row and second column: 2


In [10]:
# Slicing for rows 0 and 1, including all columns
rows_0_and_1 = two_d_array[0:2, :]

print("Rows 0 and 1:\n", rows_0_and_1)

Rows 0 and 1:
 [[1 2 3]
 [4 5 6]]


In [11]:
# Creating an array from 1 to 11
array = np.arange(1, 12)

# Finding where the array is greater than 4
greater_than_4 = array > 4

print("Array:", array)
print("Where array is greater than 4:", greater_than_4)

Array: [ 1  2  3  4  5  6  7  8  9 10 11]
Where array is greater than 4: [False False False False  True  True  True  True  True  True  True]


In [12]:
# Getting the values greater than 4
values_greater_than_4 = array[greater_than_4]

print("Values greater than 4:", values_greater_than_4)

Values greater than 4: [ 5  6  7  8  9 10 11]


In [13]:
# Boolean array where the condition (values greater than 4) is True
bool_array = array > 4

# Setting values within the array that are greater than 4 to a new value, e.g., 100
array[bool_array] = 100

print("Modified array where values greater than 4 are set to 100:", array)

Modified array where values greater than 4 are set to 100: [  1   2   3   4 100 100 100 100 100 100 100]
