<a href="https://colab.research.google.com/github/mahault/ContinuousTraining/blob/main/Numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np  # Importing NumPy

# Creating a list
my_list = [1, 2, 3, 4, 5]

# Converting the list to a NumPy array
my_array = np.array(my_list)

print(my_array)  # Displaying the NumPy array



[1 2 3 4 5]


In [2]:
# Creating a nested list
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Converting the nested list to a NumPy array
nested_array = np.array(nested_list)

print(nested_array)  # Displaying the NumPy array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Using np.arange to create an array from 1 to 10
array_range = np.arange(1, 11)

print(array_range)  # Displaying the array

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# Using np.arange to create an array of even numbers from 2 to 10
even_numbers = np.arange(2, 11, 2)

print(even_numbers)  # Displaying the array

[ 2  4  6  8 10]


In [5]:
# Creating a one-dimensional array of zeros with 5 elements
zeros_array_1d = np.zeros(5)

print("One-dimensional array of zeros:", zeros_array_1d)

One-dimensional array of zeros: [0. 0. 0. 0. 0.]


In [6]:
# Creating a two-dimensional array of zeros with 3 rows and 4 columns
zeros_array_2d = np.zeros((3, 4))

print("Two-dimensional array of zeros:\n", zeros_array_2d)

Two-dimensional array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# Creating a one-dimensional array of ones with 5 elements
ones_array_1d = np.ones(5)

print("One-dimensional array of ones:", ones_array_1d)

One-dimensional array of ones: [1. 1. 1. 1. 1.]


In [8]:
# Creating a two-dimensional array of ones with 3 rows and 4 columns
ones_array_2d = np.ones((3, 4))

print("Two-dimensional array of ones:\n", ones_array_2d)

Two-dimensional array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
# Creating an array of 10 numbers evenly spaced between 1 and 10
linspace_array = np.linspace(1, 10, 10)

print(linspace_array)  # Displaying the array

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [10]:
# Creating an array of 9 numbers evenly spaced between 1 and 10, excluding the endpoint
linspace_array_no_endpoint = np.linspace(1, 10, 9, endpoint=False)

print(linspace_array_no_endpoint)  # Displaying the array

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [11]:
# Creating a 4x4 identity matrix
identity_matrix = np.eye(4)

print("4x4 Identity Matrix:\n", identity_matrix)

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# Creating an identity matrix with 4 rows and 5 columns
identity_matrix_non_square = np.eye(4, 5)

print("Identity Matrix (4 rows, 5 columns):\n", identity_matrix_non_square)

Identity Matrix (4 rows, 5 columns):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [13]:
# Creating a one-dimensional array of 5 random numbers
random_array_1d = np.random.rand(5)

print("One-dimensional random array:", random_array_1d)

One-dimensional random array: [0.54611676 0.29626785 0.88596586 0.85203475 0.48796763]


In [14]:
# Creating a two-dimensional array of random numbers with 3 rows and 4 columns
random_array_2d = np.random.rand(3, 4)

print("Two-dimensional random array:\n", random_array_2d)

Two-dimensional random array:
 [[0.76319793 0.08871188 0.6499649  0.60116395]
 [0.32086008 0.49763427 0.4953737  0.22569973]
 [0.85886913 0.319825   0.68143819 0.42263472]]


In [15]:
# Creating a two-dimensional array of random numbers from a standard normal distribution with 3 rows and 4 columns
random_normal_array_2d = np.random.randn(3, 4)

print("Two-dimensional random normal array:\n", random_normal_array_2d)

Two-dimensional random normal array:
 [[-1.06661313 -2.51828066 -0.57108241  0.07395008]
 [-1.93762202  0.51031295  0.19978521  0.16350094]
 [-1.79854358 -0.46184302  2.05433691 -1.84388493]]


In [16]:
# Creating a one-dimensional array of 5 random numbers from a standard normal distribution
random_normal_array_1d = np.random.randn(5)

print("One-dimensional random normal array:", random_normal_array_1d)

One-dimensional random normal array: [-1.28667639 -1.85094711 -1.18425605 -1.41915169  1.20156121]


In [17]:
# Generating a single random integer
random_integer = np.random.randint(1, 10)

print("Random integer:", random_integer)

Random integer: 2


In [18]:
# Creating a one-dimensional array of 5 random integers
random_integers_1d = np.random.randint(1, 10, size=5)

print("One-dimensional array of random integers:", random_integers_1d)

One-dimensional array of random integers: [1 1 2 3 7]


In [19]:
# Setting the seed for reproducibility
np.random.seed(42)

# Now, any random operation will produce the same results in any run
random_array = np.random.rand(5)  # Creating a one-dimensional array of 5 random numbers

print("Random array with seed 42:", random_array)

Random array with seed 42: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [20]:
# Step 1: Create an array with np.arange
arange_array = np.arange(1, 26)  # Creates an array from 1 to 25

# Step 2: Create a random array with np.random.randint
random_array = np.random.randint(1, 100, size=25)  # Creates a random array of 25 numbers from 1 to 99

# Step 3: Find the shape of both arrays
print("Shape of arange array:", arange_array.shape)
print("Shape of random array:", random_array.shape)

# Step 4: Reshape the arange array to 5x5
arange_array_reshaped = arange_array.reshape(5, 5)

print("Reshaped arange array to 5x5:\n", arange_array_reshaped)

Shape of arange array: (25,)
Shape of random array: (25,)
Reshaped arange array to 5x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [21]:
# Finding the maximum value in the random array
max_value = np.max(random_array)
print("Maximum value in the random array:", max_value)

# Finding the index of the maximum value in the random array
max_index = np.argmax(random_array)
print("Index of the maximum value:", max_index)

Maximum value in the random array: 91
Index of the maximum value: 23


In [22]:
# Finding the minimum value in the random array
min_value = np.min(random_array)
print("Minimum value in the random array:", min_value)

# Finding the index of the minimum value in the random array
min_index = np.argmin(random_array)
print("Index of the minimum value:", min_index)

Minimum value in the random array: 2
Index of the minimum value: 9
